# Generated by Django 5.0.6 on 2024-06-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
